name: Windows Build

on:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'

    - run: flutter pub get
    - run: flutter build windows

    - name: Upload EXE Artifact
      uses: actions/upload-artifact@v3
      with:
        name: windows-exe
        path: build/windows/runner/Release/

