name: Build Windows EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: flutter-actions/setup-flutter@v3
        with:
          flutter-version: 'stable'

      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop

      - name: Get dependencies
        run: flutter pub get

      - name: Build for Windows
        run: flutter build windows --release

      - name: Check if .exe exists
        run: |
          if (Test-Path build\windows\x64\runner\Release\*.exe) {
            Write-Host "EXE file exists ✅"
          } else {
            Write-Host "❌ EXE file does NOT exist"
          }

      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: flutter-windows-exe
          path: build\windows\x64\runner\Release\
